#pragma once
#include <string>

namespace ModelCompNames {
	static const int NoTypNames = 13;
	static const std::string TypNames[13]{
		 "Switches",
		"Parameters",
		 "Tables",
		 "Table Parameters",
		 "State Variables",
		"Flow Variables",
		"Auxiliary Variables",
		 "Driving Variables",
		 "Files",
		 "NE",
		"DataBase",
		"RunInfo",
		 "Validation"
	};
	static const int NoElementNames = 46;
	static const std::string ElementNames[46]{
	 "Water",
	"Heat",
	"Carbon",
	"Nitrogen",
	"Phosphorus",
	"Radiation",
	"Snow",
	"Salt",
	"Methane",
	"Vapour",
	"General",
	"Temperature",
	"Water Potential",
	"Atmosphere",
	"Air",
	"Precipitation",
	"Climate",
	"Organic",
	"Dissolved Carbon",
	"Dissolved Nitrogen",
	"Dissolved Phosphorus",
	"Mineral N",
	"Mineral P",
	"Ammonium",
	"Nitrate",
	"Mycorrhize",
	"Denitrifiers",
	"Nitrofiers",
	"Anarobic gas",
	"Oxygen",
	"Manure",
	"Plant Shape",
	"Distance",
	"CO2 SOIL",
	"Time",
	"Area",
	"Plant Stress",
	"Wind Speed",
	"Global Radiation",
	"LongWave Radiation",
	"Humidity",
	"GreenHouseGas",
	"Plant Biomass",
	"Nitric Oxide",
	"Nitrous Oxide",
	"COS"
};
	static const int NoFysProcessNames = 46;
	static const std::string FysProcessNames[46]{
	"Root Water Uptake",
	 "Evapotranspiration",
	 "Transpiration",
	 "Soil Evaporation",
	 "Potential Transpiration",
	 "Interception",
	 "Turbulence",
	 "Surface Runoff",
	 "Aerodynamic Resistance",
	 "Snow Melting",
	 "Redistribution",
	 "Storage",
	 "Transport",
	 "Infiltration",
	 "Drainage",
	 "Percolation",
	 "Runoff",
	 "biotic process",
	 "Initial Flow",
	 "Shrinking",
	 "Physical Shape",
	 "Heat Extraction",
	 "Heat Pipe",
	 "Heat Source",
	 "Lower Boundary",
	 "Upper Boundary",
	 "Water Source",
	 "Salt Source",
	 "Energy Balance Partitioning",
	 "Heat Conduction",
	 "Heat Convection",
	 "Technical Regulation",
	 "Emission",
	 "Adsorption",
	 "Reflection",
	 "Mass Balance",
	 "Measurement Sensor",
	 "Geographic Position",
	 "Frost Boundary",
	 "Hysteresis",
	 "Irrigation",
	 "Budget",
	 "Geometric",
	 "Scattering",
	 "Soil Freezing",
	 "Diffusion"
	};
	static const int NoBioProcessNames = 40;
	static const std::string BioProcessNames[40]{
	 "Decomposition",
	 "Mineralisation",
	 "Nitrification",
	 "Denitrification",
	 "Respiration",
	 "Production",
	 "Oxidation",
	 "Re Allocation",
	 "Phenology",
	 "Soil Gas Dynamics",
	 "Photosynthesis",
	 "Litterfall",
	 "abiotic process",
	 "Initial NC Conditions",
	 "Initial P Conditions",
	 "Forcing Biological Conditions",
	 "Organic Transformation",
	 "Balancing Ratio",
	 "Concentration",
	 "Organic Plant Uptake",
	 "Plant Nitrogen Uptake",
	 "Plant Phosphorus Uptake",
	 "Sorption",
	 "Harvest",
	 "Grazing",
	 "Mycon Nitrogen Uptake",
	 "Soil mixing",
	 "Emergence",
	 "Plant Management",
	 "Nitrogen Fixation",
	 "Living",
	 "Non Living",
	 "Growth",
	 "WoodEating",
	 "Weathering",
	 "Methane Oxidation",
	 "Methane Production",
	 "Methane Transport",
	 "Gas Equilibrium",
	 "xx"
	};
	static const int NoGroupNames = 38;
	static const std::string GroupNames[38]{
	"Hidden",
	 "Technical",
	 "Model Structure",
	 "Numerical",
	 "Soil Profile",
	 "Soil Hydraulic",
	 "Soil Thermal",
	 "Meteorological Data",
	 "Irrigation",
	 "Plant",
	 "Interception",
	 "Potential Transpiration",
	 "Radiation properties",
	 "Soil evaporation",
	 "SnowPack",
	 "Soil frost",
	 "Soil heat flows",
	 "Soil heat pump",
	 "Soil water flows",
	 "Surface water",
	 "Water uptake",
	 "Drainage and deep percolation",
	 "Salt Tracer",
	 "Additional Variables",
	 "Plant Growth",
	 "Soil organic processes",
	 "Soil mineral N processes",
	 "Abiotic driving variables",
	 "Common abiotic responses",
	 "External N inputs",
	 "Soil Management",
	 "Additional Biotic Variables",
	 "Gas processes",
	 "Minteq",
	 "HBV",
	 "Soil mineral P Processes",
	 "External P Inputs",
	 "Validation"
	};
	static const int NoGroupCategoryNames = 9;
	static const std::string GroupCategoryNames[9]{
	 "All Modules",
	 "Atmospheric Related Processes",
	 "Plant Water Processes",
	 "Soil Heat Processes",
	 "Soil Water Processes",
	 "Nitrogen and Carbon",
	 "Nitrogen and Carbon - Below Ground",
	 "Model Structure",
	 "Model Facilities",
	};

	static const std::map<size_t, size_t> GroupCategoryNo = {
		{0,0},
		{1,8},
		{2,7},
		{3,8},
		{4,7},
		{5,4},
		{6,3},
		{7,1},
		{8,2},
		{9,2},
		{10,2},
		{11,2},
		{12,1},
		{13,1},
		{14,1},
		{15,3},
		{16,3},
		{17,3},
		{18,4},
		{19,4},
		{20,2},
		{21,4},
		{22,2},
		{23,7},
		{24,5},
		{25,6},
		{26,6},
		{27,7},
		{28,7},
		{29,5},
		{30,6},
		{31,7},
		{32,6},
		{33,6},
		{34,0},
		{35,0},
		{36,6},
		{37,8}
	};

	static const std::map <std::string, size_t> GroupCategory= {	
		{"Technical",8},
		{"Model Structure",7},
		{"Numerical",8},
		{"Soil Profile",7},
		{"Soil Hydraulic",4},
		{"Soil Thermal",3},
		{"Meteorological Data",1},

		{"Irrigation" ,4},
		{"Plant",2},
		{"Interception",2},
		{"Potential Transpiration" ,2},
		{"Radiation properties" ,1},
		{"Soil evaporation" ,1},
		{"SnowPack",1},

		{"Soil frost",3},
		{"Soil heat flows" ,3},
		{"Soil heat pump" ,3},
		{"Soil water flows" ,4},
		{"Surface water",4},
		{"Water uptake" ,2},

		{"Drainage and deep percolation" ,4},
		{"Salt Tracer" ,4},
		{"Additional Variables" ,7},
		{"Plant Growth",5},
		{"Soil organic processes",6},
		{"Soil mineral P processes",6},
		{"Soil mineral N processes",6},
		{"Abiotic driving variables",7},
		{"Common abiotic responses" ,7},
		{"External N inputs" ,5},
		{"External P inputs", 5},
		{"Soil Management" ,6},
		{"Additional Biotic Variables" ,7},
		{"Gas processes" ,6},
		{"Minteq", 6},
		{"HBV", 4},
		{"Soil mineral P Processes", 6},
		{"External P Inputs", 4},
		{"Validation" ,8} };
};






