#pragma once

enum class UNIT_TYPES {
	MEGA_HEATFLOW_UNIT,
	HEATFLOW_UNIT, HEATSOURCE_UNIT, HEATSTORE_UNIT, MEGA_HEATSTORE_VOL_UNIT,
	TEMP_UNIT, TEMPSUM_UNIT, HEATCOND_UNIT, MASS_UNIT, CARBON_MASS_UNIT, CARBON_MASSFLOW_UNIT, NITROGEN_MASS_UNIT, NITROGEN_MASSFLOW_UNIT, MASSFLOW_UNIT, WIND_SPEED_UNIT,
	WATERFLOW_UNIT, WATERCONTENT_UNIT, PRESSUREHEAD_UNIT, AREA_UNIT, MASSDENSITY_UNIT, KILO_MASSDENSITY_UNIT, INVERSE_MASS_UNIT,
	mMASS_UNIT, mMASSFLOW_UNIT, WATERMASS_UNIT, PRESSURE_UNIT, LENGTH_UNIT, LENGTH_PER_TIME_UNIT, AERODYNAMIC_RESISTANCE_UNIT,
	MIKRO_MOL_SEC_RATE, AREA_PER_TIME_UNIT, CM_AREA_PER_SEC_TIME_UNIT, GAS_MASS_UNIT, GAS_CONC_UNIT, YEAR_AGE_UNIT, PERCENTAGE, TIME_UNIT, ENERGY_MOLE,
	mMASS_LITER_UNIT, mikro_MASS_LITER_UNIT, NO_UNIT, RATECOEF_UNIT, INVERSE_WATERFLOW_UNIT, INVERSE_SQUARED_FLUX_PER_VOLUME, MASS_RATIO_UNIT, VOLUME_RATIO_UNIT,
	MIKRO_MASS_RATIO, MIKRO_MASS_FLOW_UNIT, MIKRO_MASS_RATE, TIME_MINUTE_UNIT, ANGLE_UNIT, THERMAL_CONDUCTIVY_UNIT, INVERSE_AREA_UNIT, DAYOFYEAR_UNIT,
	INVERSE_TEMP_UNIT

};